/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { CardTemplate } from './types';

export const CARD_TEMPLATES_DATA: CardTemplate[] = [
  {
    id: 'saffron-glaze',
    name: 'Saffron Glaze',
    category: 'free',
    trending: true,
    popularity: 98,
    tags: ['bold', 'warm', 'modern', 'creative'],
    style: {
      backgroundType: 'gradient',
      bgGradientStart: '#FF6B00',
      bgGradientEnd: '#060608',
      bgGradientAngle: 135,
      textColor: '#FFFFFF',
      accentColor: '#FF6B00',
      cornerRadius: 16,
      svgPattern: '3',
      showShadow: true,
      showBorder: true,
      fontFamily: 'Syne',
      layout: 'standard',
    },
  },
  {
    id: 'nordic-teal',
    name: 'Nordic Teal',
    category: 'free',
    trending: true,
    popularity: 95,
    tags: ['minimal', 'cool', 'clean', 'professional'],
    style: {
      backgroundType: 'gradient',
      bgGradientStart: '#00C9A7',
      bgGradientEnd: '#08201D',
      bgGradientAngle: 45,
      textColor: '#FFFFFF',
      accentColor: '#00C9A7',
      cornerRadius: 12,
      svgPattern: '1',
      showShadow: true,
      showBorder: false,
      fontFamily: 'Instrument Sans',
      layout: 'compact',
    },
  },
  {
    id: 'golden-aurum',
    name: 'Golden Aurum',
    category: 'premium',
    trending: true,
    popularity: 99,
    tags: ['luxury', 'exclusive', 'elegant'],
    style: {
      backgroundType: 'gradient',
      bgGradientStart: '#D4A017',
      bgGradientEnd: '#060608',
      bgGradientAngle: 135,
      textColor: '#FFFFFF',
      accentColor: '#D4A017',
      cornerRadius: 20,
      svgPattern: '8',
      showShadow: true,
      showBorder: true,
      fontFamily: 'Syne',
      layout: 'wide-avatar',
    },
  },
  {
    id: 'cosmic-dark',
    name: 'Cosmic Dark',
    category: 'free',
    trending: false,
    popularity: 82,
    tags: ['tech', 'minimal', 'futuristic'],
    style: {
      backgroundType: 'solid',
      bgSolid: '#060608',
      textColor: '#E2E8F0',
      accentColor: '#00C9A7',
      cornerRadius: 8,
      svgPattern: '5',
      showShadow: false,
      showBorder: true,
      fontFamily: 'Helvetica',
      layout: 'minimal',
    },
  },
  {
    id: 'sunset-burst',
    name: 'Sunset Burst',
    category: 'free',
    trending: true,
    popularity: 91,
    tags: ['vibrant', 'creative', 'warm'],
    style: {
      backgroundType: 'gradient',
      bgGradientStart: '#FF6B00',
      bgGradientEnd: '#D4A017',
      bgGradientAngle: 90,
      textColor: '#060608',
      accentColor: '#060608',
      cornerRadius: 16,
      svgPattern: '2',
      showShadow: true,
      showBorder: false,
      fontFamily: 'Syne',
      layout: 'bold-name',
    },
  },
  {
    id: 'mono-chic',
    name: 'Mono Chic',
    category: 'free',
    trending: false,
    popularity: 88,
    tags: ['classic', 'clean', 'monochrome'],
    style: {
      backgroundType: 'solid',
      bgSolid: '#FFFFFF',
      textColor: '#060608',
      accentColor: '#060608',
      cornerRadius: 0,
      svgPattern: 'none',
      showShadow: true,
      showBorder: true,
      fontFamily: 'Instrument Sans',
      layout: 'centered',
    },
  },
  {
    id: 'neon-cyber',
    name: 'Neon Cyber',
    category: 'premium',
    trending: true,
    popularity: 96,
    tags: ['cyberpunk', 'neon', 'high-contrast'],
    style: {
      backgroundType: 'gradient',
      bgGradientStart: '#FF007F',
      bgGradientEnd: '#060608',
      bgGradientAngle: 180,
      textColor: '#FFFFFF',
      accentColor: '#FF007F',
      cornerRadius: 14,
      svgPattern: '7',
      showShadow: true,
      showBorder: true,
      fontFamily: 'Courier New',
      layout: 'split',
    },
  },
  {
    id: 'forest-whisper',
    name: 'Forest Whisper',
    category: 'free',
    trending: false,
    popularity: 79,
    tags: ['nature', 'calm', 'earthy'],
    style: {
      backgroundType: 'gradient',
      bgGradientStart: '#1A332E',
      bgGradientEnd: '#0F1A17',
      bgGradientAngle: 120,
      textColor: '#E6F4F1',
      accentColor: '#00C9A7',
      cornerRadius: 12,
      svgPattern: '4',
      showShadow: true,
      showBorder: false,
      fontFamily: 'Instrument Sans',
      layout: 'pill-contacts',
    },
  },
  {
    id: 'ocean-mist',
    name: 'Ocean Mist',
    category: 'free',
    trending: false,
    popularity: 85,
    tags: ['cool', 'calm', 'corporate'],
    style: {
      backgroundType: 'gradient',
      bgGradientStart: '#2B6CB0',
      bgGradientEnd: '#1A365D',
      bgGradientAngle: 135,
      textColor: '#FFFFFF',
      accentColor: '#319795',
      cornerRadius: 10,
      svgPattern: '2',
      showShadow: true,
      showBorder: true,
      fontFamily: 'Arial',
      layout: 'icon-row',
    },
  },
  {
    id: 'executive-gold',
    name: 'Executive Gold',
    category: 'premium',
    trending: true,
    popularity: 97,
    tags: ['luxury', 'exclusive', 'corporate'],
    style: {
      backgroundType: 'solid',
      bgSolid: '#111115',
      textColor: '#FFFFFF',
      accentColor: '#D4A017',
      cornerRadius: 6,
      svgPattern: '9',
      showShadow: true,
      showBorder: true,
      fontFamily: 'Georgia',
      layout: 'sidebar',
    },
  },
  {
    id: 'symphony-red',
    name: 'Symphony Red',
    category: 'premium',
    trending: false,
    popularity: 76,
    tags: ['bold', 'elegant', 'vibrant'],
    style: {
      backgroundType: 'gradient',
      bgGradientStart: '#B83280',
      bgGradientEnd: '#521B41',
      bgGradientAngle: 135,
      textColor: '#FFFFFF',
      accentColor: '#F687B3',
      cornerRadius: 16,
      svgPattern: '6',
      showShadow: true,
      fontFamily: 'Syne',
      layout: 'standard',
    },
  },
  {
    id: 'vortex-purple',
    name: 'Vortex Purple',
    category: 'premium',
    trending: true,
    popularity: 94,
    tags: ['creative', 'vibrant', 'modern'],
    style: {
      backgroundType: 'gradient',
      bgGradientStart: '#805AD5',
      bgGradientEnd: '#060608',
      bgGradientAngle: 45,
      textColor: '#FFFFFF',
      accentColor: '#D6BCFA',
      cornerRadius: 24,
      svgPattern: '10',
      showShadow: true,
      fontFamily: 'Syne',
      layout: 'wide-avatar',
    },
  },
  {
    id: 'slate-minimal',
    name: 'Slate Minimal',
    category: 'free',
    trending: false,
    popularity: 84,
    tags: ['minimal', 'clean', 'business'],
    style: {
      backgroundType: 'solid',
      bgSolid: '#1E293B',
      textColor: '#F8FAFC',
      accentColor: '#38BDF8',
      cornerRadius: 8,
      svgPattern: 'none',
      showShadow: false,
      showBorder: false,
      fontFamily: 'Instrument Sans',
      layout: 'compact',
    },
  },
  {
    id: 'cherry-blossom',
    name: 'Cherry Blossom',
    category: 'free',
    trending: false,
    popularity: 81,
    tags: ['soft', 'playful', 'creative'],
    style: {
      backgroundType: 'gradient',
      bgGradientStart: '#FED7E2',
      bgGradientEnd: '#FFF5F5',
      bgGradientAngle: 90,
      textColor: '#702459',
      accentColor: '#D53F8C',
      cornerRadius: 16,
      svgPattern: '4',
      showShadow: true,
      fontFamily: 'Instrument Sans',
      layout: 'centered',
    },
  },
  {
    id: 'sandstone',
    name: 'Sandstone',
    category: 'free',
    trending: false,
    popularity: 70,
    tags: ['earthy', 'organic', 'minimal'],
    style: {
      backgroundType: 'solid',
      bgSolid: '#F5F5DC',
      textColor: '#4A3B32',
      accentColor: '#8C6239',
      cornerRadius: 12,
      svgPattern: '3',
      showShadow: true,
      fontFamily: 'Georgia',
      layout: 'minimal',
    },
  },
  {
    id: 'midnight-royal',
    name: 'Midnight Royal',
    category: 'premium',
    trending: true,
    popularity: 93,
    tags: ['luxury', 'corporate'],
    style: {
      backgroundType: 'gradient',
      bgGradientStart: '#1A365D',
      bgGradientEnd: '#000000',
      bgGradientAngle: 135,
      textColor: '#EDF2F7',
      accentColor: '#D4A017',
      cornerRadius: 18,
      svgPattern: '1',
      showShadow: true,
      fontFamily: 'Syne',
      layout: 'sidebar',
    },
  },
  {
    id: 'mint-fresh',
    name: 'Mint Fresh',
    category: 'free',
    trending: false,
    popularity: 83,
    tags: ['clean', 'vibrant', 'flat'],
    style: {
      backgroundType: 'solid',
      bgSolid: '#E6FFFA',
      textColor: '#234E52',
      accentColor: '#319795',
      cornerRadius: 6,
      svgPattern: 'none',
      showShadow: false,
      fontFamily: 'Arial',
      layout: 'pill-contacts',
    },
  },
  {
    id: 'emerald-luxury',
    name: 'Emerald Luxury',
    category: 'premium',
    trending: true,
    popularity: 98,
    tags: ['luxury', 'exclusive', 'elegant'],
    style: {
      backgroundType: 'gradient',
      bgGradientStart: '#276749',
      bgGradientEnd: '#060608',
      bgGradientAngle: 45,
      textColor: '#FFF',
      accentColor: '#D4A017',
      cornerRadius: 16,
      svgPattern: '9',
      showBorder: true,
      fontFamily: 'Georgia',
      layout: 'wide-avatar',
    },
  },
  {
    id: 'charcoal-noir',
    name: 'Charcoal Noir',
    category: 'free',
    trending: false,
    popularity: 89,
    tags: ['minimal', 'classic', 'noir'],
    style: {
      backgroundType: 'solid',
      bgSolid: '#121214',
      textColor: '#FFFFFF',
      accentColor: '#FFFFFF',
      cornerRadius: 4,
      svgPattern: 'none',
      showBorder: true,
      fontFamily: 'Helvetica',
      layout: 'bold-name',
    },
  },
  {
    id: 'cyber-saffron',
    name: 'Cyber Saffron',
    category: 'premium',
    trending: true,
    popularity: 96,
    tags: ['tech', 'cyberpunk', 'vibrant'],
    style: {
      backgroundType: 'gradient',
      bgGradientStart: '#FF6B00',
      bgGradientEnd: '#1A365D',
      bgGradientAngle: 90,
      textColor: '#FFFFFF',
      accentColor: '#00C9A7',
      cornerRadius: 20,
      svgPattern: '10',
      fontFamily: 'Syne',
      layout: 'split',
    },
  },
  {
    id: 'copper-edge',
    name: 'Copper Edge',
    category: 'premium',
    trending: false,
    popularity: 75,
    tags: ['classic', 'vintage'],
    style: {
      backgroundType: 'gradient',
      bgGradientStart: '#B7791F',
      bgGradientEnd: '#2D3748',
      bgGradientAngle: 180,
      textColor: '#FFFFF0',
      accentColor: '#ED8936',
      cornerRadius: 12,
      svgPattern: '2',
      fontFamily: 'Georgia',
      layout: 'icon-row',
    },
  },
  {
    id: 'lavender-breeze',
    name: 'Lavender Breeze',
    category: 'free',
    trending: false,
    popularity: 82,
    tags: ['soft', 'clean'],
    style: {
      backgroundType: 'gradient',
      bgGradientStart: '#EBF8FF',
      bgGradientEnd: '#EBF4FF',
      bgGradientAngle: 45,
      textColor: '#2B6CB0',
      accentColor: '#4299E1',
      cornerRadius: 15,
      svgPattern: 'none',
      fontFamily: 'Instrument Sans',
      layout: 'centered',
    },
  },
  {
    id: 'holographic-glitch',
    name: 'Holo Glitch',
    category: 'premium',
    trending: true,
    popularity: 95,
    tags: ['cyberpunk', 'experimental'],
    style: {
      backgroundType: 'gradient',
      bgGradientStart: '#4FD1C5',
      bgGradientEnd: '#B794F4',
      bgGradientAngle: 135,
      textColor: '#1A202C',
      accentColor: '#121214',
      cornerRadius: 16,
      svgPattern: '5',
      fontFamily: 'Courier New',
      layout: 'wide-avatar',
    },
  },
  {
    id: 'crimson-gold',
    name: 'Crimson Gold',
    category: 'premium',
    trending: false,
    popularity: 88,
    tags: ['bold', 'luxury'],
    style: {
      backgroundType: 'gradient',
      bgGradientStart: '#9B2C2C',
      bgGradientEnd: '#1A202C',
      bgGradientAngle: 45,
      textColor: '#FFF',
      accentColor: '#D4A017',
      cornerRadius: 14,
      svgPattern: '8',
      fontFamily: 'Georgia',
      layout: 'sidebar',
    },
  },
  {
    id: 'electric-blue',
    name: 'Electric Blue',
    category: 'free',
    trending: true,
    popularity: 90,
    tags: ['tech', 'bold', 'vibrant'],
    style: {
      backgroundType: 'gradient',
      bgGradientStart: '#3182CE',
      bgGradientEnd: '#0A2540',
      bgGradientAngle: 135,
      textColor: '#FFFFFF',
      accentColor: '#63B3ED',
      cornerRadius: 10,
      svgPattern: '3',
      fontFamily: 'Helvetica',
      layout: 'compact',
    },
  },
  {
    id: 'sand-dunes',
    name: 'Sand Dunes',
    category: 'free',
    trending: false,
    popularity: 73,
    tags: ['calm', 'earthy'],
    style: {
      backgroundType: 'solid',
      bgSolid: '#EDF2F7',
      textColor: '#2D3748',
      accentColor: '#ED8936',
      cornerRadius: 16,
      svgPattern: '4',
      fontFamily: 'Instrument Sans',
      layout: 'standard',
    },
  },
  {
    id: 'vampire-goth',
    name: 'Vamp Noir',
    category: 'premium',
    trending: false,
    popularity: 80,
    tags: ['noir', 'exclusive'],
    style: {
      backgroundType: 'solid',
      bgSolid: '#0B0000',
      textColor: '#FFF5F5',
      accentColor: '#E53E3E',
      cornerRadius: 4,
      svgPattern: '6',
      fontFamily: 'Georgia',
      layout: 'bold-name',
    },
  },
  {
    id: 'sweet-peach',
    name: 'Sweet Peach',
    category: 'free',
    trending: false,
    popularity: 78,
    tags: ['soft', 'warm'],
    style: {
      backgroundType: 'gradient',
      bgGradientStart: '#FEEBC8',
      bgGradientEnd: '#FFD2D2',
      bgGradientAngle: 120,
      textColor: '#7B341E',
      accentColor: '#DD6B20',
      cornerRadius: 24,
      svgPattern: 'none',
      fontFamily: 'Instrument Sans',
      layout: 'pill-contacts',
    },
  },
  {
    id: 'glam-aurora',
    name: 'Glam Aurora',
    category: 'premium',
    trending: true,
    popularity: 97,
    tags: ['vibrant', 'luxury'],
    style: {
      backgroundType: 'gradient',
      bgGradientStart: '#E2E8F0',
      bgGradientEnd: '#D4A017',
      bgGradientAngle: 45,
      textColor: '#1A202C',
      accentColor: '#060608',
      cornerRadius: 20,
      svgPattern: '1',
      fontFamily: 'Syne',
      layout: 'centered',
    },
  },
  {
    id: 'ultimate-titanium',
    name: 'Titanium Sleek',
    category: 'premium',
    trending: true,
    popularity: 99,
    tags: ['tech', 'luxury', 'noir'],
    style: {
      backgroundType: 'gradient',
      bgGradientStart: '#4A5568',
      bgGradientEnd: '#1A202C',
      bgGradientAngle: 135,
      textColor: '#EDF2F7',
      accentColor: '#CBD5E0',
      cornerRadius: 8,
      svgPattern: '7',
      fontFamily: 'Helvetica',
      layout: 'sidebar',
    },
  },
];
